### ISSUE TITLE
gcr http 404 https://gitlab.com/api/v1/builds/register.json

### ISSUE THREAD

**Issue by Ridermansb** [evanlucas/gcr#15] opened 2015-09-25 11:16 UTC
For my config file ...

```json
{
  "url": "https://gitlab.com/ci",
  "buildDir": "/home/ridermansb/GitLabRunnerNode",
  "git": "/usr/bin/git",
  "token": "<myToken>"
}
```
When I execute `gcr -t <myToken>`

The result is: 

```bash
gcr info [client] checking for builds...
gcr http 404 https://gitlab.com/api/v1/builds/register.json
gcr info [client] checking for builds...
gcr http 404 https://gitlab.com/api/v1/builds/register.json
gcr info [client] checking for builds...
gcr http 404 https://gitlab.com/api/v1/builds/register.json
gcr info [client] checking for builds...
gcr http 404 https://gitlab.com/api/v1/builds/register.json
gcr info [client] checking for builds...
gcr http 404 https://gitlab.com/api/v1/builds/register.json
gcr info [client] checking for builds...
gcr http 404 https://gitlab.com/api/v1/builds/register.json
gcr info [client] checking for builds...
gcr http 404 https://gitlab.com/api/v1/builds/register.json
gcr info [client] checking for builds...
gcr http 404 https://gitlab.com/api/v1/buil
```

**Comment by evanlucas** [comment] 2015-09-25 13:34
Duplicate of https://github.com/evanlucas/gcr/issues/14.

> The 404 you are getting is normal. Whenever the client checks for builds, if no builds are available, the request returns a 404. When that request returns a 200, it tells the runner to actually start a new build.

**Closed by evanlucas** 2015-09-25 13:34 UTC
